language: node_js

node_js:
  - "stable"

sudo: false

cache:
  directories:
    - "node_modules"

script:
# Run code checks
  - npm run compat
# Run tests
  - npm run test
  - npm run test_node
# Generate docs
  - npm run docs
# Deploy 
  - git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/Open-EO/openeo-js-client.git gh-pages
  - cd gh-pages
  - cp -R ../docs/@openeo/js-client/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  name: openEO CI
  email: openeo.ci@uni-muenster.de
  local-dir: gh-pages
  on:
    all_branches: true